name: 'dbt_hiring'
version: '1.0.0'

profile: 'dbt_hiring'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  dbt_hiring:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: view
      +schema: marts
    analytics:
      +materialized: view
      +schema: analytics
